tap 'homebrew/bundle'
tap 'homebrew/cask'
tap 'homebrew/cask-fonts'

brew 'coreutils'
brew 'ctop'
brew 'exa'
brew 'fselect'
brew 'fx'
brew 'fzy'
brew 'git'
brew 'neovim'
brew 'opam'
brew 'openjdk'
brew 'ripgrep'
brew 'tig'

# Cask
cask 'dropbox'
cask 'font-fira-code'
cask 'font-victor-mono'
cask 'grandperspective'
cask 'iina'
cask 'insomnia'
cask 'kindlegen'
cask 'the-unarchiver'
cask 'itsycal'
