theme = "tokyonight_storm"

[editor]
bufferline = "multiple"
line-number = "relative"
rulers = [120]

[editor.whitespace.render]
space = "none"
tab = "all"
newline = "none"

[editor.whitespace.characters]
tab = "→"
tabpad = "·"

[editor.indent-guides]
render = true
skip-levels = 1

[editor.lsp]
display-messages = true

[editor.soft-wrap]
enable = false
wrap-at-text-width = true 
