theme = "monokai_pro_octagon"

[editor]
line-number = "relative"

[editor.whitespace.render]
space = "none"
tab = "all"
newline = "none"

[editor.whitespace.characters]
tab = "→"
tabpad = "·"

[editor.lsp]
display-messages = true
